.env.sample
next.config.js
package.json
src/components/layout/index.tsx
src/components/layout/styles.tsx
src/components/navbar/components/desktop/components/nav_items/index.tsx
src/styles/mixins.ts
yarn.lock

Layout css

---

semantic/src/themes/default/globals/site.variables
src/screens/desmos/components/desmos_body/components/desmos_header/config.tsx
src/screens/desmos/components/desmos_body/components/desmos_header/index.tsx
src/screens/desmos/components/desmos_body/components/desmos_header/styles.tsx
src/screens/desmos/components/desmos_body/components/mobile/styles.tsx

fix: global font

---

src/screens/desmos/components/mooncake_body/components/mooncake_details/styles.tsx
src/screens/desmos/components/mooncake_body/components/mooncake_img/styles.tsx

fix image on safari

---

src/components/navbar/components/mobile/components/nav_body/styles.tsx
src/components/navbar/components/mobile/hooks.tsx

fix: mobile nav closes if it hit desktop width

---

src/components/layout/index.tsx
src/components/layout/styles.tsx
src/screens/404/index.tsx
src/screens/404/styles.tsx
src/screens/desmos/components/desmos_body/components/desktop/styles.tsx
src/screens/desmos/components/mooncake_body/components/desktop/styles.tsx

update: layout to handle 404

---

package.json
yarn.lock

fix: vulerability

---

public/static/locales/en/footer.json
src/components/footer/components/desktop/index.tsx
src/components/footer/components/desktop/styles.tsx
src/components/footer/components/footer_items/index.tsx
src/components/footer/components/footer_items/styles.tsx
src/components/footer/components/forbole/styles.tsx
src/components/footer/components/mobile/styles.tsx
src/components/footer/components/social_media/styles.tsx
src/components/footer/components/subscribe/styles.tsx

wip: fix/footer

---

next.config.js
src/screens/about/components/milestones/config.tsx
src/screens/about/components/milestones/index.tsx
tsconfig.json

closes #72 
fixes compiling to production error (fake) and fix about css styling

Fix production compile error

---

.env.defaults
next.config.js
server/index.ts

update: env files

---

src/screens/about/components/header/index.tsx
src/screens/about/components/header/styles.tsx
src/screens/about/components/milestones/styles.tsx
src/screens/about/components/opportunities/components/opening/styles.tsx
src/screens/about/components/opportunities/styles.tsx
src/screens/about/components/team/styles.tsx
src/screens/about/components/what_we_do/styles.tsx

update: about

---

src/screens/desmos/components/mooncake_body/components/desktop/styles.tsx
src/screens/desmos/config.tsx

desmos page ui

---

public/static/locales/en/contact.json
server/index.ts
src/screens/contact/components/contact_message/hooks.tsx
src/screens/contact/components/contact_message/index.tsx

toast added

---

src/utils/network_info.ts

change height socket cosmos

---

src/screens/blog_details/styles.tsx

Fixed overflow issue in blog detail
closes #140 
- [v] Targeted PR against correct branch.
- [v] Re-reviewed `Files changed` in the Github PR explorer.

Fixed overflow

---

server/index.ts
src/screens/blog/components/blog_posts/index.tsx
src/screens/contact/components/contact_message/hooks.tsx
src/screens/contact/components/contact_message/index.tsx
src/screens/desmos/components/desmos_body/components/desktop/index.tsx
src/screens/desmos/components/desmos_body/components/mobile/index.tsx

update: desmos

---

src/components/layout/index.tsx
src/models/post.ts
src/pages/blog/[title].tsx
src/screens/blog_details/index.tsx

wip: meta info for seo

---

src/screens/contact/components/contact_header/styles.tsx
src/screens/contact/styles.tsx

Contact Page css

---

src/screens/home/index.tsx
yarn.lock

Fix home og title and dependencies

---

src/screens/tag/index.tsx

tag page rendering

---

src/components/navbar/components/mobile/index.tsx
src/components/tag_details_loader/hooks.tsx
src/components/tag_details_loader/index.tsx
src/components/tag_details_loader/styles.tsx

mobile repsonsiveness fix

---

src/screens/team/components/team/components/member/styles.tsx
src/screens/team/components/team/styles.tsx

Team Page - mobile and tablet view fix

---

src/components/footer/components/footer_items/styles.tsx

footer desktop view fix

---

src/components/footer/components/social_media/config.ts
src/screens/contact/config.tsx

Social Media update

---

src/screens/home/components/news/components/news_header/styles.tsx
src/screens/home/components/supported_networks/styles.tsx

Home Page - ui review comments

---

src/screens/about/components/milestones/index.tsx
src/screens/about/components/milestones/styles.tsx

About Page - desktop view [UI review]

---

public/static/locales/en/blog.json
server/index.ts
src/pages/author/[author]/index.tsx
src/screens/author/components/author_posts/components/post/index.tsx
src/screens/author/components/author_posts/hooks.tsx
src/screens/author/components/author_posts/index.tsx
src/screens/author/components/author_posts/interface.ts
src/screens/author/index.tsx
src/screens/blog_details/components/social_media/index.tsx

fix: Blog / Author Page

---

src/screens/about/components/header/styles.tsx
src/screens/about/components/what_we_do/index.tsx
src/screens/about/components/what_we_do/styles.tsx

About Page - UI change

---

src/components/animated_network/styles.tsx

Component - animated network ui

---

src/screens/stake_now/components/calculate_rewards/components/networks/config.ts
src/screens/stake_now/components/calculate_rewards/index.tsx
src/screens/stake_now/config.tsx
src/utils/network_info.ts

Stake Now - Calculated Networks

---

public/static/locales/en/stake_now.json
src/components/animated_network/index.tsx
src/components/animated_network/interfaces.tsx
src/components/animated_network/styles.tsx
src/screens/home/components/supported_networks/config.ts
src/screens/home/components/supported_networks/index.tsx
src/screens/stake_now/config.tsx
src/utils/network_info.ts

animated networks update

---

package.json
src/screens/stake_now/components/calculate_rewards/components/networks/config.ts
src/screens/stake_now/components/forbole_stakes/index.tsx
src/screens/stake_now/components/forbole_stakes/styles.tsx
src/screens/stake_now/config.tsx
src/utils/network_info.ts
yarn.lock

Stake now/animated usd

---

src/screens/stake_now/components/forbole_stakes/components/carousel_networks/index.tsx
src/screens/stake_now/components/forbole_stakes/components/network_block/index.tsx
src/screens/stake_now/components/forbole_stakes/config.tsx
src/screens/stake_now/components/forbole_stakes/hooks.tsx
src/screens/stake_now/components/forbole_stakes/index.tsx
src/screens/stake_now/components/forbole_stakes/styles.tsx

Stake Now links

---

src/screens/products/components/big_dipper/styles.tsx
src/screens/products/components/products_header/components/product_block/styles.tsx
src/screens/products/components/products_header/styles.tsx

Products Page

---

src/screens/author/index.tsx
src/screens/tag/index.tsx

default featureImage added on author and tag pages

---

package.json
yarn.lock

Upgrea `react-dom` to meet the min requirements of `nextjs v10.2`

upgrade react-dom

---

package.json
src/components/icons/disclaimer.svg
src/components/icons/index.tsx
src/screens/stake_now/components/calculate_rewards/index.tsx
src/screens/stake_now/components/calculate_rewards/styles.tsx
yarn.lock

Stake Now page - calculator/disclaimer

---

src/screens/author/index.tsx
src/screens/blog/index.tsx
src/screens/tag/components/tag_posts/components/post/index.tsx
src/screens/tag/index.tsx

fix - defaultImage

---

public/static/locales/en/footer.json
src/components/footer/config.js

footer content

---

src/screens/products/components/big_dipper/components/big_dipper_content/index.tsx
src/screens/products/components/products_header/components/product_block/config.tsx

Updates https://cosmos.bigdipper.live/ to https://bigdipper.live/ in the correct locations

update: big dipper link to big dipper landing

---

server/index.ts
src/pages/author/index.tsx

closes #306 
Added an `index` file under `src/pages/author` and commented out the route handling on `/server` to see if Nextjs can handle the dynamic routing for author page upon direct visit on the production site
@kwunyeung

added index for src/pages/author

---

src/screens/about/components/header/styles.tsx
src/screens/about/components/milestones/styles.tsx
src/screens/about/components/what_we_do/styles.tsx
src/screens/about/styles.tsx

UI Review - About Page

---

public/static/locales/en/stake_now.json
src/screens/products/components/big_dipper/components/big_dipper_content/styles.tsx
src/screens/products/components/products_header/components/product_block/index.tsx
src/screens/products/components/products_header/components/product_block/styles.tsx
src/screens/products/components/products_header/styles.tsx

UI Update - Products Page

---

src/screens/stake_now/components/forbole_stakes/components/carousel_networks/styles.tsx
src/screens/stake_now/components/forbole_stakes/styles.tsx

update: Stake Now Page UI

---

src/screens/stake_now/components/calculate_rewards/hooks.tsx

Stake Now Page - calculation fix

---

src/screens/careers/components/opportunities/components/opening/styles.tsx

ui update - job openings
